default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clock_event_development
test:
  <<: *default
  database: clock_event_test
production:
  <<: *default
  database: clock_event_production
  username: clock_event
  password: <%= ENV['CLOCK_EVENT_DATABASE_PASSWORD'] %>
